# backend/routers/reports.py
from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import FileResponse
from typing import Optional
from pathlib import Path
import tempfile
import os

router = APIRouter(prefix="/api/report", tags=["reports"])


def generate_demo_pdf(job_id: Optional[str] = None) -> str:
    """
    Generate a demo PDF report.
    Returns the path to the generated PDF file.
    """
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet
    except ImportError:
        raise HTTPException(
            status_code=500, 
            detail="reportlab not installed. Install with: pip install reportlab"
        )
    
    # Create temp file for PDF
    temp_dir = tempfile.gettempdir()
    pdf_path = os.path.join(temp_dir, f"coatvision_report_{job_id or 'demo'}.pdf")
    
    # Create PDF document
    doc = SimpleDocTemplate(pdf_path, pagesize=A4)
    styles = getSampleStyleSheet()
    story = []
    
    # Title
    title = Paragraph("CoatVision Analysis Report", styles['Heading1'])
    story.append(title)
    story.append(Spacer(1, 12))
    
    # Job info
    if job_id:
        job_info = Paragraph(f"Job ID: {job_id}", styles['Normal'])
        story.append(job_info)
        story.append(Spacer(1, 12))
    
    # Demo metrics table
    data = [
        ['Metric', 'Value', 'Status'],
        ['CVI (Coating Visual Index)', '87.5%', 'Good'],
        ['CQI (Coating Quality Index)', '92.3%', 'Excellent'],
        ['Coverage', '95.8%', 'Excellent'],
        ['Color Uniformity', '88.2%', 'Good'],
        ['Surface Smoothness', '91.0%', 'Excellent'],
    ]
    
    table = Table(data, colWidths=[200, 100, 80])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ]))
    story.append(table)
    story.append(Spacer(1, 24))
    
    # Summary
    summary = Paragraph(
        "This is a demo report generated by CoatVision. "
        "The actual analysis uses OpenCV-based image processing to calculate "
        "coating quality metrics.",
        styles['Normal']
    )
    story.append(summary)
    
    # Build PDF
    doc.build(story)
    
    return pdf_path


@router.get("/demo")
async def get_demo_report(job_id: Optional[str] = Query(None, description="Optional job ID")):
    """
    Generate and return a demo PDF report.
    Optionally accepts a job_id query parameter.
    """
    try:
        pdf_path = generate_demo_pdf(job_id)
        return FileResponse(
            pdf_path,
            media_type="application/pdf",
            filename=f"coatvision_report_{job_id or 'demo'}.pdf"
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/status")
async def report_status():
    """Get report generation status."""
    return {
        "status": "ok",
        "available_formats": ["pdf"],
        "demo_endpoint": "/api/report/demo"
    }
