#!/bin/bash
# CoatVision Backend API Setup Script
# This script installs dependencies, configures .env, and runs the server locally.
# Compatible with macOS and Linux

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_banner() {
    echo ""
    echo "============================================"
    echo "   CoatVision Backend API Setup"
    echo "============================================"
    echo ""
}

# Get script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BACKEND_DIR="$PROJECT_ROOT/backend"

print_banner

# Check if backend directory exists
if [ ! -d "$BACKEND_DIR" ]; then
    log_error "Backend directory not found at $BACKEND_DIR"
    exit 1
fi

cd "$BACKEND_DIR"
log_info "Working directory: $BACKEND_DIR"

# Step 1: Check Python installation
log_info "Checking Python installation..."
if command -v python3 &> /dev/null; then
    PYTHON_CMD="python3"
    PYTHON_VERSION=$(python3 --version 2>&1)
    log_success "Found $PYTHON_VERSION"
elif command -v python &> /dev/null; then
    PYTHON_CMD="python"
    PYTHON_VERSION=$(python --version 2>&1)
    log_success "Found $PYTHON_VERSION"
else
    log_error "Python is not installed. Please install Python 3.8 or higher."
    exit 1
fi

# Step 2: Create virtual environment
log_info "Setting up virtual environment..."
if [ ! -d ".venv" ]; then
    $PYTHON_CMD -m venv .venv
    log_success "Virtual environment created"
else
    log_info "Virtual environment already exists"
fi

# Activate virtual environment
if [ -f ".venv/bin/activate" ]; then
    source .venv/bin/activate
    log_success "Virtual environment activated"
else
    log_error "Failed to find virtual environment activation script"
    exit 1
fi

# Step 3: Upgrade pip
log_info "Upgrading pip..."
pip install --upgrade pip --quiet
log_success "pip upgraded"

# Step 4: Install dependencies
log_info "Installing Python dependencies..."
if [ -f "requirements.txt" ]; then
    pip install -r requirements.txt --quiet
    log_success "Dependencies installed from requirements.txt"
else
    log_warning "requirements.txt not found, installing core dependencies..."
    pip install fastapi uvicorn python-multipart pydantic openai opencv-python numpy reportlab --quiet
    log_success "Core dependencies installed"
fi

# Step 5: Configure .env file
log_info "Configuring environment variables..."
ENV_FILE="$BACKEND_DIR/.env"
ENV_EXAMPLE="$BACKEND_DIR/.env.example"

if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << 'EOF'
# CoatVision Backend Environment Configuration
# Generated by setup-backend.sh

# Server Configuration
HOST=0.0.0.0
PORT=8000
DEBUG=true

# OpenAI API Key (required for AI features)
# Get your API key from: https://platform.openai.com/api-keys
OPENAI_API_KEY=your_openai_api_key_here

# Database Configuration (optional - for future use)
# DATABASE_URL=sqlite:///./coatvision.db

# CORS Configuration
CORS_ORIGINS=*

# Upload Configuration
MAX_UPLOAD_SIZE=10485760
UPLOAD_DIR=./uploads
EOF
    log_success ".env file created"
    log_warning "Please edit .env and add your OpenAI API key before running the server"
else
    log_info ".env file already exists"
fi

# Create .env.example for reference
if [ ! -f "$ENV_EXAMPLE" ]; then
    cat > "$ENV_EXAMPLE" << 'EOF'
# CoatVision Backend Environment Configuration Example
# Copy this file to .env and fill in your values

# Server Configuration
HOST=0.0.0.0
PORT=8000
DEBUG=true

# OpenAI API Key (required for AI features)
OPENAI_API_KEY=your_openai_api_key_here

# Database Configuration (optional)
# DATABASE_URL=sqlite:///./coatvision.db

# CORS Configuration
CORS_ORIGINS=*

# Upload Configuration
MAX_UPLOAD_SIZE=10485760
UPLOAD_DIR=./uploads
EOF
    log_success ".env.example file created for reference"
fi

# Step 6: Create necessary directories
log_info "Creating necessary directories..."
mkdir -p "$BACKEND_DIR/uploads"
mkdir -p "$BACKEND_DIR/outputs"
log_success "Directories created"

# Step 7: Run the server
echo ""
echo "============================================"
log_success "Setup complete!"
echo "============================================"
echo ""
log_info "To start the server, run:"
echo "    cd $BACKEND_DIR"
echo "    source .venv/bin/activate"
echo "    # For development:"
echo "    uvicorn main:app --host 127.0.0.1 --port 8000 --reload"
echo "    # For production:"
echo "    uvicorn main:app --host 0.0.0.0 --port 8000"
echo ""

# Ask if user wants to start the server now
read -p "Do you want to start the server now? (y/n): " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    log_info "Starting CoatVision Backend API (development mode)..."
    log_info "Server will be available at: http://localhost:8000"
    log_info "API documentation at: http://localhost:8000/docs"
    log_warning "Note: Using --reload for development. For production, omit --reload"
    log_info "Press Ctrl+C to stop the server"
    echo ""
    uvicorn main:app --host 127.0.0.1 --port 8000 --reload
fi
