#!/bin/bash
# CoatVision React Native Mobile App Setup Script
# This script installs dependencies, configures the backend API endpoint, and starts the app using Expo.
# Compatible with macOS and Linux

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_banner() {
    echo ""
    echo "============================================"
    echo "   CoatVision Mobile App Setup"
    echo "============================================"
    echo ""
}

# Get script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
MOBILE_DIR="$PROJECT_ROOT/mobile"

print_banner

# Check if mobile directory exists
if [ ! -d "$MOBILE_DIR" ]; then
    log_error "Mobile directory not found at $MOBILE_DIR"
    exit 1
fi

cd "$MOBILE_DIR"
log_info "Working directory: $MOBILE_DIR"

# Step 1: Check Node.js installation
log_info "Checking Node.js installation..."
if command -v node &> /dev/null; then
    NODE_VERSION=$(node --version)
    log_success "Found Node.js $NODE_VERSION"
else
    log_error "Node.js is not installed. Please install Node.js 18 or higher."
    log_info "Download from: https://nodejs.org/"
    exit 1
fi

# Check npm
if command -v npm &> /dev/null; then
    NPM_VERSION=$(npm --version)
    log_success "Found npm $NPM_VERSION"
else
    log_error "npm is not installed. Please install npm."
    exit 1
fi

# Step 2: Install dependencies
log_info "Installing npm dependencies..."
if [ -f "package.json" ]; then
    npm install
    log_success "Dependencies installed"
else
    log_error "package.json not found"
    exit 1
fi

# Step 3: Check for Expo CLI
log_info "Checking Expo CLI..."
if ! command -v npx &> /dev/null; then
    log_error "npx is not available. Please update npm."
    exit 1
fi
log_success "Expo CLI available via npx"

# Step 4: Configure backend API endpoint
log_info "Configuring backend API endpoint..."
ENV_FILE="$MOBILE_DIR/.env"
ENV_EXAMPLE="$MOBILE_DIR/.env.example"

# Detect local IP for physical device testing
get_local_ip() {
    if command -v ip &> /dev/null; then
        # Use a common public IP to determine the local interface
        ip route get 8.8.8.8 2>/dev/null | awk '{for(i=1;i<=NF;i++)if($i=="src"){print $(i+1);exit}}' || echo "localhost"
    elif command -v ifconfig &> /dev/null; then
        ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -1 || echo "localhost"
    else
        echo "localhost"
    fi
}

LOCAL_IP=$(get_local_ip)

if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << EOF
# CoatVision Mobile App Environment Configuration
# Generated by setup-mobile.sh

# Backend API Configuration
# For Android emulator use: http://10.0.2.2:8000/api
# For iOS simulator use: http://localhost:8000/api
# For physical device use your computer's LAN IP (detected: $LOCAL_IP)
EXPO_PUBLIC_API_BASE=http://localhost:8000/api

# For physical device testing, uncomment and use:
# EXPO_PUBLIC_API_BASE=http://$LOCAL_IP:8000/api

# App Configuration
EXPO_PUBLIC_APP_NAME=CoatVision
EXPO_PUBLIC_APP_VERSION=0.1.0
EOF
    log_success ".env file created"
    log_warning "Edit .env to configure API endpoint for your testing environment"
else
    log_info ".env file already exists"
fi

# Create .env.example for reference
if [ ! -f "$ENV_EXAMPLE" ]; then
    cat > "$ENV_EXAMPLE" << 'EOF'
# CoatVision Mobile App Environment Configuration Example
# Copy this file to .env and configure for your environment

# Backend API Configuration
# For Android emulator use: http://10.0.2.2:8000/api
# For iOS simulator use: http://localhost:8000/api
# For physical device use your computer's LAN IP
EXPO_PUBLIC_API_BASE=http://localhost:8000/api

# App Configuration
EXPO_PUBLIC_APP_NAME=CoatVision
EXPO_PUBLIC_APP_VERSION=0.1.0
EOF
    log_success ".env.example file created for reference"
fi

# Step 5: Create app.json if it doesn't exist
APP_JSON="$MOBILE_DIR/app.json"
if [ ! -f "$APP_JSON" ]; then
    log_info "Creating app.json configuration..."
    cat > "$APP_JSON" << 'EOF'
{
  "expo": {
    "name": "CoatVision",
    "slug": "coatvision",
    "version": "0.1.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.coatvision.app"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "package": "com.coatvision.app"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      [
        "expo-camera",
        {
          "cameraPermission": "Allow CoatVision to access your camera for coating analysis."
        }
      ]
    ]
  }
}
EOF
    log_success "app.json created"
fi

# Step 6: Create assets directory if it doesn't exist
ASSETS_DIR="$MOBILE_DIR/assets"
if [ ! -d "$ASSETS_DIR" ]; then
    log_info "Creating assets directory..."
    mkdir -p "$ASSETS_DIR"
    log_success "Assets directory created"
fi

# Complete
echo ""
echo "============================================"
log_success "Setup complete!"
echo "============================================"
echo ""
log_info "Your local IP address: $LOCAL_IP"
log_info "Make sure the backend is running at http://localhost:8000"
echo ""
log_info "To start the app, run one of the following:"
echo "    cd $MOBILE_DIR"
echo ""
echo "    # For development (opens Expo Go app or browser)"
echo "    npx expo start"
echo ""
echo "    # For Android emulator"
echo "    npx expo start --android"
echo ""
echo "    # For iOS simulator (macOS only)"
echo "    npx expo start --ios"
echo ""
echo "    # For web browser"
echo "    npx expo start --web"
echo ""

# Ask if user wants to start the app now
read -p "Do you want to start the Expo development server now? (y/n): " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    log_info "Starting Expo development server..."
    log_info "Scan the QR code with Expo Go app on your mobile device"
    log_info "Press Ctrl+C to stop the server"
    echo ""
    npx expo start
fi
