#!/bin/bash
# CoatVision Admin Dashboard Setup Script
# This script installs dependencies, creates .env.local file, and runs the dashboard locally.
# Compatible with macOS and Linux

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_banner() {
    echo ""
    echo "============================================"
    echo "   CoatVision Admin Dashboard Setup"
    echo "============================================"
    echo ""
}

# Get script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FRONTEND_DIR="$PROJECT_ROOT/frontend"

print_banner

# Check if frontend directory exists
if [ ! -d "$FRONTEND_DIR" ]; then
    log_error "Frontend directory not found at $FRONTEND_DIR"
    exit 1
fi

cd "$FRONTEND_DIR"
log_info "Working directory: $FRONTEND_DIR"

# Step 1: Check Node.js installation
log_info "Checking Node.js installation..."
if command -v node &> /dev/null; then
    NODE_VERSION=$(node --version)
    log_success "Found Node.js $NODE_VERSION"
else
    log_error "Node.js is not installed. Please install Node.js 18 or higher."
    log_info "Download from: https://nodejs.org/"
    exit 1
fi

# Check npm
if command -v npm &> /dev/null; then
    NPM_VERSION=$(npm --version)
    log_success "Found npm $NPM_VERSION"
else
    log_error "npm is not installed. Please install npm."
    exit 1
fi

# Step 2: Install dependencies
log_info "Installing npm dependencies..."
if [ -f "package.json" ]; then
    npm install
    log_success "Dependencies installed"
else
    log_error "package.json not found"
    exit 1
fi

# Step 3: Configure .env.local file
log_info "Configuring environment variables..."
ENV_FILE="$FRONTEND_DIR/.env.local"
ENV_EXAMPLE="$FRONTEND_DIR/.env.example"

if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << 'EOF'
# CoatVision Dashboard Environment Configuration
# Generated by setup-dashboard.sh

# Supabase Configuration (required for authentication and data storage)
# Get your credentials from: https://app.supabase.com/
VITE_SUPABASE_URL=your_supabase_project_url
VITE_SUPABASE_ANON_KEY=your_supabase_anon_key

# Backend API Configuration
VITE_API_BASE_URL=http://localhost:8000/api

# App Configuration
VITE_APP_NAME=CoatVision Dashboard
VITE_APP_VERSION=0.1.0
EOF
    log_success ".env.local file created"
    log_warning "Please edit .env.local and add your Supabase credentials"
else
    log_info ".env.local file already exists"
fi

# Create .env.example for reference
if [ ! -f "$ENV_EXAMPLE" ]; then
    cat > "$ENV_EXAMPLE" << 'EOF'
# CoatVision Dashboard Environment Configuration Example
# Copy this file to .env.local and fill in your values

# Supabase Configuration (required for authentication and data storage)
# Get your credentials from: https://app.supabase.com/
VITE_SUPABASE_URL=your_supabase_project_url
VITE_SUPABASE_ANON_KEY=your_supabase_anon_key

# Backend API Configuration
VITE_API_BASE_URL=http://localhost:8000/api

# App Configuration
VITE_APP_NAME=CoatVision Dashboard
VITE_APP_VERSION=0.1.0
EOF
    log_success ".env.example file created for reference"
fi

# Complete
echo ""
echo "============================================"
log_success "Setup complete!"
echo "============================================"
echo ""
log_info "Make sure to configure your Supabase credentials in .env.local"
log_info "Make sure the backend is running at http://localhost:8000"
echo ""
log_info "To start the dashboard, run:"
echo "    cd $FRONTEND_DIR"
echo "    npm run dev"
echo ""
log_info "The dashboard will be available at: http://localhost:3000"
echo ""

# Ask if user wants to start the dashboard now
read -p "Do you want to start the dashboard now? (y/n): " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    log_info "Starting CoatVision Dashboard..."
    log_info "Dashboard will be available at: http://localhost:3000"
    log_info "Press Ctrl+C to stop the server"
    echo ""
    npm run dev
fi
