# CoatVision Admin Dashboard Setup Script for Windows
# This script installs dependencies, creates .env.local file, and runs the dashboard locally.
# Compatible with Windows PowerShell and PowerShell Core

param(
    [switch]$StartDashboard = $false,
    [switch]$Help = $false
)

# Stop on errors
$ErrorActionPreference = "Stop"

# Colors for output
function Write-Info { param($Message) Write-Host "[INFO] $Message" -ForegroundColor Cyan }
function Write-Success { param($Message) Write-Host "[SUCCESS] $Message" -ForegroundColor Green }
function Write-Warning { param($Message) Write-Host "[WARNING] $Message" -ForegroundColor Yellow }
function Write-Error { param($Message) Write-Host "[ERROR] $Message" -ForegroundColor Red }

function Print-Banner {
    Write-Host ""
    Write-Host "============================================" -ForegroundColor Blue
    Write-Host "   CoatVision Admin Dashboard Setup" -ForegroundColor Blue
    Write-Host "============================================" -ForegroundColor Blue
    Write-Host ""
}

if ($Help) {
    Write-Host "CoatVision Admin Dashboard Setup Script"
    Write-Host ""
    Write-Host "Usage: .\setup-dashboard.ps1 [-StartDashboard] [-Help]"
    Write-Host ""
    Write-Host "Options:"
    Write-Host "  -StartDashboard    Start the dashboard after setup"
    Write-Host "  -Help              Show this help message"
    exit 0
}

Print-Banner

# Get script directory and project root
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$FrontendDir = Join-Path $ProjectRoot "frontend"

# Check if frontend directory exists
if (-not (Test-Path $FrontendDir)) {
    Write-Error "Frontend directory not found at $FrontendDir"
    exit 1
}

Set-Location $FrontendDir
Write-Info "Working directory: $FrontendDir"

# Step 1: Check Node.js installation
Write-Info "Checking Node.js installation..."
try {
    $nodeVersion = & node --version 2>&1
    Write-Success "Found Node.js $nodeVersion"
} catch {
    Write-Error "Node.js is not installed. Please install Node.js 18 or higher."
    Write-Info "Download from: https://nodejs.org/"
    exit 1
}

# Check npm
try {
    $npmVersion = & npm --version 2>&1
    Write-Success "Found npm $npmVersion"
} catch {
    Write-Error "npm is not installed. Please install npm."
    exit 1
}

# Step 2: Install dependencies
Write-Info "Installing npm dependencies..."
$packageJson = Join-Path $FrontendDir "package.json"
if (Test-Path $packageJson) {
    & npm install
    Write-Success "Dependencies installed"
} else {
    Write-Error "package.json not found"
    exit 1
}

# Step 3: Configure .env.local file
Write-Info "Configuring environment variables..."
$envFile = Join-Path $FrontendDir ".env.local"
$envExample = Join-Path $FrontendDir ".env.example"

if (-not (Test-Path $envFile)) {
    $envContent = @"
# CoatVision Dashboard Environment Configuration
# Generated by setup-dashboard.ps1

# Supabase Configuration (required for authentication and data storage)
# Get your credentials from: https://app.supabase.com/
VITE_SUPABASE_URL=your_supabase_project_url
VITE_SUPABASE_ANON_KEY=your_supabase_anon_key

# Backend API Configuration
VITE_API_BASE_URL=http://localhost:8000/api

# App Configuration
VITE_APP_NAME=CoatVision Dashboard
VITE_APP_VERSION=0.1.0
"@
    Set-Content -Path $envFile -Value $envContent
    Write-Success ".env.local file created"
    Write-Warning "Please edit .env.local and add your Supabase credentials"
} else {
    Write-Info ".env.local file already exists"
}

# Create .env.example for reference
if (-not (Test-Path $envExample)) {
    $envExampleContent = @"
# CoatVision Dashboard Environment Configuration Example
# Copy this file to .env.local and fill in your values

# Supabase Configuration (required for authentication and data storage)
# Get your credentials from: https://app.supabase.com/
VITE_SUPABASE_URL=your_supabase_project_url
VITE_SUPABASE_ANON_KEY=your_supabase_anon_key

# Backend API Configuration
VITE_API_BASE_URL=http://localhost:8000/api

# App Configuration
VITE_APP_NAME=CoatVision Dashboard
VITE_APP_VERSION=0.1.0
"@
    Set-Content -Path $envExample -Value $envExampleContent
    Write-Success ".env.example file created for reference"
}

# Complete
Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Success "Setup complete!"
Write-Host "============================================" -ForegroundColor Green
Write-Host ""
Write-Info "Make sure to configure your Supabase credentials in .env.local"
Write-Info "Make sure the backend is running at http://localhost:8000"
Write-Host ""
Write-Info "To start the dashboard, run:"
Write-Host "    cd $FrontendDir"
Write-Host "    npm run dev"
Write-Host ""
Write-Info "The dashboard will be available at: http://localhost:3000"
Write-Host ""

# Ask if user wants to start the dashboard now
if (-not $StartDashboard) {
    $response = Read-Host "Do you want to start the dashboard now? (y/n)"
    if ($response -match "^[Yy]") {
        $StartDashboard = $true
    }
}

if ($StartDashboard) {
    Write-Info "Starting CoatVision Dashboard..."
    Write-Info "Dashboard will be available at: http://localhost:3000"
    Write-Info "Press Ctrl+C to stop the server"
    Write-Host ""
    & npm run dev
}
