# CoatVision Backend API Setup Script for Windows
# This script installs dependencies, configures .env, and runs the server locally.
# Compatible with Windows PowerShell and PowerShell Core

param(
    [switch]$StartServer = $false,
    [switch]$Help = $false
)

# Stop on errors
$ErrorActionPreference = "Stop"

# Colors for output
function Write-Info { param($Message) Write-Host "[INFO] $Message" -ForegroundColor Cyan }
function Write-Success { param($Message) Write-Host "[SUCCESS] $Message" -ForegroundColor Green }
function Write-Warning { param($Message) Write-Host "[WARNING] $Message" -ForegroundColor Yellow }
function Write-Error { param($Message) Write-Host "[ERROR] $Message" -ForegroundColor Red }

function Print-Banner {
    Write-Host ""
    Write-Host "============================================" -ForegroundColor Blue
    Write-Host "   CoatVision Backend API Setup" -ForegroundColor Blue
    Write-Host "============================================" -ForegroundColor Blue
    Write-Host ""
}

if ($Help) {
    Write-Host "CoatVision Backend Setup Script"
    Write-Host ""
    Write-Host "Usage: .\setup-backend.ps1 [-StartServer] [-Help]"
    Write-Host ""
    Write-Host "Options:"
    Write-Host "  -StartServer    Start the server after setup"
    Write-Host "  -Help           Show this help message"
    exit 0
}

Print-Banner

# Get script directory and project root
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$BackendDir = Join-Path $ProjectRoot "backend"

# Check if backend directory exists
if (-not (Test-Path $BackendDir)) {
    Write-Error "Backend directory not found at $BackendDir"
    exit 1
}

Set-Location $BackendDir
Write-Info "Working directory: $BackendDir"

# Step 1: Check Python installation
Write-Info "Checking Python installation..."
$pythonCmd = $null
try {
    $pythonVersion = & python --version 2>&1
    if ($pythonVersion -match "Python 3") {
        $pythonCmd = "python"
        Write-Success "Found $pythonVersion"
    }
} catch {
    try {
        $pythonVersion = & python3 --version 2>&1
        if ($pythonVersion -match "Python 3") {
            $pythonCmd = "python3"
            Write-Success "Found $pythonVersion"
        }
    } catch {
        Write-Error "Python is not installed. Please install Python 3.8 or higher."
        exit 1
    }
}

if (-not $pythonCmd) {
    Write-Error "Python 3 is required. Please install Python 3.8 or higher."
    exit 1
}

# Step 2: Create virtual environment
Write-Info "Setting up virtual environment..."
$venvPath = Join-Path $BackendDir ".venv"
if (-not (Test-Path $venvPath)) {
    & $pythonCmd -m venv .venv
    Write-Success "Virtual environment created"
} else {
    Write-Info "Virtual environment already exists"
}

# Activate virtual environment
$activateScript = Join-Path $venvPath "Scripts\Activate.ps1"
if (Test-Path $activateScript) {
    & $activateScript
    Write-Success "Virtual environment activated"
} else {
    Write-Error "Failed to find virtual environment activation script"
    exit 1
}

# Step 3: Upgrade pip
Write-Info "Upgrading pip..."
& pip install --upgrade pip --quiet
Write-Success "pip upgraded"

# Step 4: Install dependencies
Write-Info "Installing Python dependencies..."
$requirementsFile = Join-Path $BackendDir "requirements.txt"
if (Test-Path $requirementsFile) {
    & pip install -r requirements.txt --quiet
    Write-Success "Dependencies installed from requirements.txt"
} else {
    Write-Warning "requirements.txt not found, installing core dependencies..."
    & pip install fastapi uvicorn python-multipart pydantic openai opencv-python numpy reportlab --quiet
    Write-Success "Core dependencies installed"
}

# Step 5: Configure .env file
Write-Info "Configuring environment variables..."
$envFile = Join-Path $BackendDir ".env"
$envExample = Join-Path $BackendDir ".env.example"

if (-not (Test-Path $envFile)) {
    $envContent = @"
# CoatVision Backend Environment Configuration
# Generated by setup-backend.ps1

# Server Configuration
HOST=0.0.0.0
PORT=8000
DEBUG=true

# OpenAI API Key (required for AI features)
# Get your API key from: https://platform.openai.com/api-keys
OPENAI_API_KEY=your_openai_api_key_here

# Database Configuration (optional - for future use)
# DATABASE_URL=sqlite:///./coatvision.db

# CORS Configuration
CORS_ORIGINS=*

# Upload Configuration
MAX_UPLOAD_SIZE=10485760
UPLOAD_DIR=./uploads
"@
    Set-Content -Path $envFile -Value $envContent
    Write-Success ".env file created"
    Write-Warning "Please edit .env and add your OpenAI API key before running the server"
} else {
    Write-Info ".env file already exists"
}

# Create .env.example for reference
if (-not (Test-Path $envExample)) {
    $envExampleContent = @"
# CoatVision Backend Environment Configuration Example
# Copy this file to .env and fill in your values

# Server Configuration
HOST=0.0.0.0
PORT=8000
DEBUG=true

# OpenAI API Key (required for AI features)
OPENAI_API_KEY=your_openai_api_key_here

# Database Configuration (optional)
# DATABASE_URL=sqlite:///./coatvision.db

# CORS Configuration
CORS_ORIGINS=*

# Upload Configuration
MAX_UPLOAD_SIZE=10485760
UPLOAD_DIR=./uploads
"@
    Set-Content -Path $envExample -Value $envExampleContent
    Write-Success ".env.example file created for reference"
}

# Step 6: Create necessary directories
Write-Info "Creating necessary directories..."
New-Item -ItemType Directory -Path (Join-Path $BackendDir "uploads") -Force | Out-Null
New-Item -ItemType Directory -Path (Join-Path $BackendDir "outputs") -Force | Out-Null
Write-Success "Directories created"

# Step 7: Complete
Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Success "Setup complete!"
Write-Host "============================================" -ForegroundColor Green
Write-Host ""
Write-Info "To start the server, run:"
Write-Host "    cd $BackendDir"
Write-Host "    .\.venv\Scripts\Activate.ps1"
Write-Host "    # For development:"
Write-Host "    uvicorn main:app --host 127.0.0.1 --port 8000 --reload"
Write-Host "    # For production:"
Write-Host "    uvicorn main:app --host 0.0.0.0 --port 8000"
Write-Host ""

# Ask if user wants to start the server now
if (-not $StartServer) {
    $response = Read-Host "Do you want to start the server now? (y/n)"
    if ($response -match "^[Yy]") {
        $StartServer = $true
    }
}

if ($StartServer) {
    Write-Info "Starting CoatVision Backend API (development mode)..."
    Write-Info "Server will be available at: http://localhost:8000"
    Write-Info "API documentation at: http://localhost:8000/docs"
    Write-Warning "Note: Using --reload for development. For production, omit --reload"
    Write-Info "Press Ctrl+C to stop the server"
    Write-Host ""
    & uvicorn main:app --host 127.0.0.1 --port 8000 --reload
}
