# CoatVision React Native Mobile App Setup Script for Windows
# This script installs dependencies, configures the backend API endpoint, and starts the app using Expo.
# Compatible with Windows PowerShell and PowerShell Core

param(
    [switch]$StartApp = $false,
    [string]$Platform = "",
    [switch]$Help = $false
)

# Stop on errors
$ErrorActionPreference = "Stop"

# Colors for output
function Write-Info { param($Message) Write-Host "[INFO] $Message" -ForegroundColor Cyan }
function Write-Success { param($Message) Write-Host "[SUCCESS] $Message" -ForegroundColor Green }
function Write-Warning { param($Message) Write-Host "[WARNING] $Message" -ForegroundColor Yellow }
function Write-Error { param($Message) Write-Host "[ERROR] $Message" -ForegroundColor Red }

function Print-Banner {
    Write-Host ""
    Write-Host "============================================" -ForegroundColor Blue
    Write-Host "   CoatVision Mobile App Setup" -ForegroundColor Blue
    Write-Host "============================================" -ForegroundColor Blue
    Write-Host ""
}

if ($Help) {
    Write-Host "CoatVision Mobile App Setup Script"
    Write-Host ""
    Write-Host "Usage: .\setup-mobile.ps1 [-StartApp] [-Platform <platform>] [-Help]"
    Write-Host ""
    Write-Host "Options:"
    Write-Host "  -StartApp           Start Expo after setup"
    Write-Host "  -Platform <name>    Platform to start (android, ios, web)"
    Write-Host "  -Help               Show this help message"
    exit 0
}

Print-Banner

# Get script directory and project root
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$MobileDir = Join-Path $ProjectRoot "mobile"

# Check if mobile directory exists
if (-not (Test-Path $MobileDir)) {
    Write-Error "Mobile directory not found at $MobileDir"
    exit 1
}

Set-Location $MobileDir
Write-Info "Working directory: $MobileDir"

# Step 1: Check Node.js installation
Write-Info "Checking Node.js installation..."
try {
    $nodeVersion = & node --version 2>&1
    Write-Success "Found Node.js $nodeVersion"
} catch {
    Write-Error "Node.js is not installed. Please install Node.js 18 or higher."
    Write-Info "Download from: https://nodejs.org/"
    exit 1
}

# Check npm
try {
    $npmVersion = & npm --version 2>&1
    Write-Success "Found npm $npmVersion"
} catch {
    Write-Error "npm is not installed. Please install npm."
    exit 1
}

# Step 2: Install dependencies
Write-Info "Installing npm dependencies..."
$packageJson = Join-Path $MobileDir "package.json"
if (Test-Path $packageJson) {
    & npm install
    Write-Success "Dependencies installed"
} else {
    Write-Error "package.json not found"
    exit 1
}

# Step 3: Check for Expo CLI
Write-Info "Checking Expo CLI..."
try {
    & npx --version 2>&1 | Out-Null
    Write-Success "Expo CLI available via npx"
} catch {
    Write-Error "npx is not available. Please update npm."
    exit 1
}

# Step 4: Configure backend API endpoint
Write-Info "Configuring backend API endpoint..."
$envFile = Join-Path $MobileDir ".env"
$envExample = Join-Path $MobileDir ".env.example"

# Detect local IP for physical device testing
function Get-LocalIP {
    try {
        $ip = (Get-NetIPAddress -AddressFamily IPv4 -InterfaceAlias "Wi-Fi" -ErrorAction SilentlyContinue).IPAddress
        if ($ip) { return $ip }
        $ip = (Get-NetIPAddress -AddressFamily IPv4 -InterfaceAlias "Ethernet" -ErrorAction SilentlyContinue).IPAddress
        if ($ip) { return $ip }
        $ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.*" } | Select-Object -First 1).IPAddress
        if ($ip) { return $ip }
    } catch {
        return "localhost"
    }
    return "localhost"
}

$localIP = Get-LocalIP

if (-not (Test-Path $envFile)) {
    $envContent = @"
# CoatVision Mobile App Environment Configuration
# Generated by setup-mobile.ps1

# Backend API Configuration
# For Android emulator use: http://10.0.2.2:8000/api
# For iOS simulator use: http://localhost:8000/api
# For physical device use your computer's LAN IP (detected: $localIP)
EXPO_PUBLIC_API_BASE=http://localhost:8000/api

# For physical device testing, uncomment and use:
# EXPO_PUBLIC_API_BASE=http://${localIP}:8000/api

# App Configuration
EXPO_PUBLIC_APP_NAME=CoatVision
EXPO_PUBLIC_APP_VERSION=0.1.0
"@
    Set-Content -Path $envFile -Value $envContent
    Write-Success ".env file created"
    Write-Warning "Edit .env to configure API endpoint for your testing environment"
} else {
    Write-Info ".env file already exists"
}

# Create .env.example for reference
if (-not (Test-Path $envExample)) {
    $envExampleContent = @"
# CoatVision Mobile App Environment Configuration Example
# Copy this file to .env and configure for your environment

# Backend API Configuration
# For Android emulator use: http://10.0.2.2:8000/api
# For iOS simulator use: http://localhost:8000/api
# For physical device use your computer's LAN IP
EXPO_PUBLIC_API_BASE=http://localhost:8000/api

# App Configuration
EXPO_PUBLIC_APP_NAME=CoatVision
EXPO_PUBLIC_APP_VERSION=0.1.0
"@
    Set-Content -Path $envExample -Value $envExampleContent
    Write-Success ".env.example file created for reference"
}

# Step 5: Create app.json if it doesn't exist
$appJson = Join-Path $MobileDir "app.json"
if (-not (Test-Path $appJson)) {
    Write-Info "Creating app.json configuration..."
    $appJsonContent = @'
{
  "expo": {
    "name": "CoatVision",
    "slug": "coatvision",
    "version": "0.1.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.coatvision.app"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "package": "com.coatvision.app"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": [
      [
        "expo-camera",
        {
          "cameraPermission": "Allow CoatVision to access your camera for coating analysis."
        }
      ]
    ]
  }
}
'@
    Set-Content -Path $appJson -Value $appJsonContent
    Write-Success "app.json created"
}

# Step 6: Create assets directory if it doesn't exist
$assetsDir = Join-Path $MobileDir "assets"
if (-not (Test-Path $assetsDir)) {
    Write-Info "Creating assets directory..."
    New-Item -ItemType Directory -Path $assetsDir -Force | Out-Null
    Write-Success "Assets directory created"
}

# Complete
Write-Host ""
Write-Host "============================================" -ForegroundColor Green
Write-Success "Setup complete!"
Write-Host "============================================" -ForegroundColor Green
Write-Host ""
Write-Info "Your local IP address: $localIP"
Write-Info "Make sure the backend is running at http://localhost:8000"
Write-Host ""
Write-Info "To start the app, run one of the following:"
Write-Host "    cd $MobileDir"
Write-Host ""
Write-Host "    # For development (opens Expo Go app or browser)"
Write-Host "    npx expo start"
Write-Host ""
Write-Host "    # For Android emulator"
Write-Host "    npx expo start --android"
Write-Host ""
Write-Host "    # For iOS simulator (macOS only)"
Write-Host "    npx expo start --ios"
Write-Host ""
Write-Host "    # For web browser"
Write-Host "    npx expo start --web"
Write-Host ""

# Ask if user wants to start the app now
if (-not $StartApp) {
    $response = Read-Host "Do you want to start the Expo development server now? (y/n)"
    if ($response -match "^[Yy]") {
        $StartApp = $true
    }
}

if ($StartApp) {
    Write-Info "Starting Expo development server..."
    Write-Info "Scan the QR code with Expo Go app on your mobile device"
    Write-Info "Press Ctrl+C to stop the server"
    Write-Host ""
    
    if ($Platform -eq "android") {
        & npx expo start --android
    } elseif ($Platform -eq "ios") {
        & npx expo start --ios
    } elseif ($Platform -eq "web") {
        & npx expo start --web
    } else {
        & npx expo start
    }
}
